src/components/google_map_marker.ts
src/custom_typings/google_maps.d.ts
src/services/marker_manager.ts

When using a `<sebm-google-map-marker>` inside a `<sebm-google-map>`, you
can now set a single-character label:
```html
<sebm-google-map-marker [latitude]="lat" [longitude]="lng"
[label]="myLabel"></sebm-google-map-marker>
```

feat(sebmGoogleMapMarker): support basic label

---

src/core/core-module.ts
src/core/directives.ts
src/core/directives/google-map-kml-layer.ts
src/core/directives/google-map.ts
src/core/map-types.ts
src/core/services.ts
src/core/services/google-maps-types.ts
src/core/services/managers/kml-layer-manager.ts

This introduces a new Directive called `<sebm-google-map-kml-layer>`
Closes #734

feat(*): Support KML Layer

---

assets/release/README.md
tsconfig.es2015.json

The UMD file was not ES5 compatible.
Fixes #783
BREAKING CHANGE:
The files under `/esm` are ES5 (before: ES2015) based with ES2015 modules.
In the real world, this should not cause troubles.

fix(core.umd.js): ship ES5 compatible UMD file

---

src/core/directives/map.ts
src/core/services/google-maps-types.ts

This PR adds support for all the control options.  You can provide either a boolean value, or the options object for each control e.g.:
```
(zoomControl)='true' 
(zoomControl)='{ position: X }'
```
Also created '_mapChangeableOptions' which I think simplifies how the changeable options are mapped.
I updated the map types to support the Control options.  I believe the existing type there was invalid, because the ControlPosition is actually an integer enum.  I'm not sure why this file doesn't import the google maps typings directly.
Finally, I couldn't see where disableDoubleClickZoom was being set, so I've hooked up that input too

Add support for control options

---

src/core/directives/map.ts

When you call the triggerResize method of AgmMap, the map gets recentered
automaticaly.
BREAKING CHANGE
Recentering of the map after triggerResize call is now the default behavoir.
You can have the previous behavoir with triggerResize(false).

feat(AgmMap): recentering for triggerResize

---

src/core/services/google-maps-api-wrapper.ts
src/core/services/google-maps-types.ts

This PR adds the missing method `panBy` from Pull Request #911  with the appropriate commit squashing and message.

feat(GoogleMapsAPIWrapper): add panBy method

---

packages/core/services/managers/info-window-manager.ts

Fix for disableAutoPan @Input() property on agm-info-window component not correctly setting disableAutoPan option on Google Map InfoWindows.

Pass the disableAutoPan property through to the Google Maps InfoWindow options for infowindow creation.

---

packages/js-marker-clusterer/README.md
packages/js-marker-clusterer/directives/marker-cluster.ts

the marker cluster needs it's own `InfoWindowManager`, otherwise `InfoWindowManager` would be injected with the root `MarkerManager` instead of the `ClusterManager`
fixes #1126

fix(AgmMarkerCluster): fixes info windows

---

packages/js-marker-clusterer/package.tpl.json

@agm/js-markerer-cluster was depending on 1.0.0-beta.0 but only beta.1 has the required changes to `MakerManager`

chore: depend on correct version

---

packages/snazzy-info-window/directives/snazzy-info-window.ts

Add closeOnMapClick to options passed to SnazzyInfoWindow.
Fix #1118

fix(snazzy-info-window): fix passing of closeOnMapClick param

---

packages/core/services/maps-api-loader/lazy-maps-api-loader.ts

Check in lazy loader if google maps script was loaded and maps are initialized in window.

Fix(lazy-loader): Add check if google maps script was already loaded

---

packages/core/services/maps-api-loader/lazy-maps-api-loader.ts

I would like to reuse the currently available lazy api loader and extend it. Therefore it would be useful to not be that restrictive with properties and methods so they can be used in classes extending this one.

refactor(core) make lazyapi loader extendable

---

packages/js-marker-clusterer/services/managers/cluster-manager.ts

`Delete a marker` unit test failed because `setMap(null)` was not called in the `deleteMarker` method

Cluster manager fix

---

packages/core/directives/marker.ts
packages/core/services/google-maps-types.ts
packages/core/services/managers/marker-manager.spec.ts
packages/core/services/managers/marker-manager.ts
packages/js-marker-clusterer/services/managers/cluster-manager.spec.ts
packages/js-marker-clusterer/services/managers/cluster-manager.ts

Add functionality to create a complex marker icon
#517 #1013 #1057 #1088
Example:
```
<agm-marker
[latitude]="location.latitude"
[longitude]="location.longitude"
[icon]="location.icon">
</agm-marker>
```

Added complex marker icon

---

packages/core/directives/map.ts
packages/core/services/google-maps-api-wrapper.ts

When `AgmMap` destroyed, it stays in memory because it has bound event listeners.
Closes: #1207

fix memory leak when AgmMap is destroyed

---

packages/core/directives/marker.ts

feat AgmMarker: include marker instance in markerClick emitter
it is usefull to be able to work directly with the marker clicked in the event handler, instead of writing extra code to determine it

include marker instance in markerClick emitter

---

packages/core/directives/map.ts

fix(Map): fitBounds values that are undefined/null

---

packages/core/services/maps-api-loader/lazy-maps-api-loader.spec.ts
packages/core/services/maps-api-loader/lazy-maps-api-loader.ts

Fixes #1573
This changes the default Google Maps API version to `quarterly`.
More details about the new versioning schema here: https://developers.google.com/maps/documentation/javascript/versions

feat(GoogleMapsAPILoader): change default API version

---

packages/core/directives/map.ts
packages/core/services/google-maps-types.ts

Adds new option to map configuration: `restriction`
```
export interface MapRestriction {
latLngBounds: LatLngBounds|LatLngBoundsLiteral;
strictBounds?: boolean;
}
```
Notice: It requires google maps api at least `v3.35`.
Resolves: #1623

feat(AgmMap): add area restriction option

---

packages/core/directives/map.ts

Fix fitBounds input in map.ts directive causing timeout in protractor
tests. _fitBoundsSubscription is now run outside angular ngZone to
prevent protractor from waiting for sample and timer rxjs operators
to sync map bounds.
closes #1548

feat(AgmMap): fix fitBounds causing protractor timeout

---

packages/core/directives/map.ts
packages/core/services/google-maps-types.ts

Issue #1581
Adds the Google Maps Option `tilt`. 
By default for AGM value: `0` to disable it. Set it to `45` to enable it.
The type `number` not `0 | 45` is correctly in my option and conform with the google api type specs.

feat(AgmMap): Tilt option.

---

packages/core/directives/map.ts
packages/core/services/google-maps-types.ts

Adding the `controlSize` properties - addressing issue: https://github.com/SebastianM/angular-google-maps/issues/1646

Update map.ts - Adding controlSize property

---

packages/core/directives/polyline-point.spec.ts
packages/core/directives/polyline-point.ts

Bug already discussed in the following issue:
https://github.com/SebastianM/angular-google-maps/issues/1268
When updating only the latitude or longitude of a PolylinePoint, an error is thrown by ngOnChanges.

fix(PolylinePoint): prevent accessing undefined variable on change

---

packages/core/directives/map.ts

fixes #1586
Add two more checks before using  google.maps.LatLngBounds() in _updateBounds function

fix: google is not defined when using fitBounds

---

packages/core/directives/fit-bounds.ts

distinctUntilChanged did wrong comparison, causing every element to reevaluate fitBounds on every cycle

fix(FitBounds): correct distinct algorythm

---

packages/core/core.module.ts
packages/core/directives.ts
packages/core/directives/fit-bounds.ts
packages/core/directives/map.ts
packages/core/directives/transit-layer.ts
packages/core/services.ts
packages/core/services/google-maps-api-wrapper.ts
packages/core/services/google-maps-types.ts
packages/core/services/managers/transit-layer-manager.spec.ts
packages/core/services/managers/transit-layer-manager.ts

- Added new Directive called <agm-transit-layer>
- Added test
Note: general styles applied to the map may affect the transit layer:
Change the default color for transit layer
`{
featureType: 'transit', 
elementType: 'geometry',
stylers: [{color: '#2f3948'}] 
}`
Hide labels of the transit layer on the map
`{
featureType: 'transit',
elementType: 'labels.icon',
stylers: [{visibility: 'off'}] 
}`
Also note that transit information is not available in some locations. Visit https://developers.google.com/maps/documentation/javascript/trafficlayer#transit_layer for more info.

feat(*): Support for Transit Layer

---

packages/core/directives/marker.ts
packages/core/services/managers/marker-manager.spec.ts
packages/core/services/managers/marker-manager.ts

adds animationChange output to connect to google's animation_changed event, and
enable two way binding
fixes: #1681

 fix(AgmMarker): animationChange output 

---

packages/core/directives/map.ts

This pull request exposes 'tilesloaded' event on AgmMap component. GoogleMaps API reference [here](https://developers.google.com/maps/documentation/javascript/reference/map#Map.tilesloaded).
Closes #1701

feat(AgmMap): Add tilesloaded event to AgmMap

---

packages/core/directives/polyline-point.spec.ts
packages/core/directives/polyline-point.ts

feat(FitBounds): add fitBounds to agm-polyline-point

---

packages/core/directives/map.ts
packages/core/index.ts
packages/core/services/google-maps-api-wrapper.ts
packages/core/services/google-maps-types.ts

add optional `fitBoundsPadding` property that when defined will be forwarded to the native maps `fitBounds` method.

feat(AgmMap): add optional fit bounds padding

---

packages/core/map-types.ts
packages/core/services.ts
packages/core/services/geocoder-service.spec.ts
packages/core/services/geocoder-service.ts
packages/core/services/google-maps-types.ts

- add geocoder service
- add geocoder unit tests
- add geocoder related typing
implements #1694

feat(AgmGeocoder): add geocoder service and tests

---

packages/core/services/maps-api-loader/lazy-maps-api-loader.spec.ts
packages/core/services/maps-api-loader/lazy-maps-api-loader.ts

the language of google maps should default to angular's LOCALE_ID, and not en-US

feat: google map language to default to LOCALE_ID

---

packages/core/directives/marker.ts
packages/core/map-types.ts
packages/core/services/google-maps-types.ts

Add MarkerIcon type

---

packages/core/directives/map.ts

If the fitBounds are not automatically computed, unsubscription from existing fitBoundsSubscription should follow.
Fixing an edge case problem where if user was using automatic fitBounds calculation suddenly switches to fitBounds object (e.g. LngLatBoundsLiteral) and then provided fitBounds by user would be overwritten by the active subscription.
This is quick fix.

unsubscribing fitBoundsSubscription when necessary

---

packages/core/src/lib/directives/map.ts
packages/core/src/lib/services/managers/circle-manager.ts
packages/core/src/lib/services/managers/rectangle-manager.ts

manager classes ran getNativeMap to call wrapper class which itself
waited for map to be ready. Change to create an unresolved promise
immediately
fixes: #1855
fixed #1857

fix: eager promise creation to avoid NPE
