src/core/directives/map.ts
src/core/services/google-maps-types.ts

You can now set the mapTypeId with an input named mapTypeId.
Closes #774

feat(AgmMap): add mapTypeId support

---

CHANGELOG.md

copyedit changelog

---

src/core/directives/circle.ts
src/core/directives/data-layer.ts
src/core/directives/info-window.ts
src/core/directives/kml-layer.ts
src/core/directives/map.ts
src/core/directives/marker.ts
src/core/directives/polygon.ts
src/core/directives/polyline.ts

The API documentation tool changes, so it's possible to use @Input and @Output decorators.
// cc @lazarljubenovic

Use @Input / @Output decorators

---

packages/js-marker-clusterer/README.md

add simple Readme for js-marker-clusterer

---

packages/core/services/maps-api-loader/lazy-maps-api-loader.ts

I believe this is the only OpaqueToken in the code, if there is more then do point them out but a search did not find any. This change hopefully will help with Angular 5.

Change OpaqueToken to InjectionToken

---

packages/core/directives/data-layer.ts

fix(datalayer): smarter ngOnChanges

---

docs/content/guides/basic-info-window.md
docs/themes/angular-google-maps/layouts/_default/single.html

docs: add guide for basic info windows

---

packages/core/directives/map.ts
packages/core/services/google-maps-api-wrapper.ts
packages/core/services/google-maps-types.ts

Add the event emitter for google map's maptypeid_changed event

feat(AgmMap): EventEmitter for maptypeid_changed event

---

docs/content/guides/snazzy-info-window/custom-info-windows-with-snazzy-info-window.md

Fixed minor typo in snazzy-info-window guide

---

packages/core/directives/marker.ts
packages/core/map-types.ts

Google Maps API allow to pass string or object with defined structure. This PR will allow to do the same and follow official API.

Allow to pass marker's label as object

---

README.md

chore(docs): fix upcoming misspell

---

packages/core/services/maps-api-loader/lazy-maps-api-loader.spec.ts
packages/core/services/maps-api-loader/lazy-maps-api-loader.ts

This prevents that we have multiple create script tags for the
google maps api.
Fixes #315
Fixes #775
Fixes #1260

fix(LazyMapsAPILoader): multiple google maps api scripts on page

---

packages/core/core.module.ts
packages/core/directives.ts
packages/core/directives/map.ts
packages/core/directives/rectangle.ts
packages/core/services.ts
packages/core/services/google-maps-api-wrapper.ts
packages/core/services/google-maps-types.ts
packages/core/services/managers/rectangle-manager.spec.ts
packages/core/services/managers/rectangle-manager.ts

add rectangle support (rebase version)

---

packages/core/directives/marker.ts

I stumbled upon [this PR](https://github.com/SebastianM/angular-google-maps/pull/1223/files/32940118e1ce63f4620f775c922176888a6e14db), which seems to be put on hold by the original author.
I thought I'd give it a try so I incorporated your change request. Let me know if this is different from what you had in mind.
Fixes #771

Auto-convert string to Number for marker input

---

packages/core/directives/marker.ts

Adds feature as requested in #1362. 
Edit: 
I should probably mention that `npm run clang:format ` modifies 42 files. Is that unintentioned, or is the code not formatted properly?

feat: add rightclick event to marker

---

packages/core/directives/polygon.ts

see bug report:
https://github.com/SebastianM/angular-google-maps/issues/1202

fixed polygon double click

---

packages/core/directives/marker.ts

Not sure if this was overlooked but the current version the drag and dragStart outputs do not work

Add drag and dragStart to outputs array

---

docs/content/guides/js-marker-clusterer/markers-cluster-with-js-marker-clusterer.md
packages/js-marker-clusterer/directives/marker-cluster.ts
packages/js-marker-clusterer/services/managers/cluster-manager.spec.ts
packages/js-marker-clusterer/services/managers/cluster-manager.ts

adds support for defining a custom calculator function
resolves #1510
relates to #1349

feat(cluster): add calculator option

---

packages/core/directives/polygon.ts
packages/core/directives/polyline.ts
packages/core/services/google-maps-types.ts
packages/core/services/managers/polygon-manager.spec.ts
packages/core/services/managers/polygon-manager.ts
packages/core/services/managers/polyline-manager.ts
packages/core/utils/mvcarray-utils.ts

Adds the MVCArray type, and allow to bind to changes in the paths of
AgmPolygon and AgmPolyline

feat(polygon, polyline): add path change event

---

packages/core/core.module.ts

fix(fit-bounds) enable local builds

---

docs/content/guides/snazzy-info-window/custom-info-windows-with-snazzy-info-window.md

update references to .angular-cli.json to `angular.json`, as per Angular 6
See https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4

docs(SnazzyInfoWindow): remove .angular-cli.json

---

packages/core/services/google-maps-api-wrapper.ts
packages/core/services/managers/circle-manager.spec.ts
packages/core/services/managers/circle-manager.ts

fixes circle error when strokeWeight is enabled by using the correct values
for strokePosition
fixes: #770

fix(AgmCircle): circle strokeWeight error

---

packages/core/core.module.ts
packages/core/directives.ts
packages/core/directives/polyline-icon.ts
packages/core/directives/polyline-point.ts
packages/core/directives/polyline.ts
packages/core/map-types.ts
packages/core/services/google-maps-types.ts
packages/core/services/managers/polyline-manager.spec.ts
packages/core/services/managers/polyline-manager.ts

Enable polyline icons
fixes: #721

feat(Polyline): add IconSequences to Polylines

---

.github/ISSUE_TEMPLATE.md
.gitignore
docs/content/guides/getting-started.md

- set issue template to point to working stackblitz, instead of non
working plunker
- add npm pack files to .gitignore
- minor updates to getting started guide

chore: update issue template, gitignore, gs-guide

---

packages/core/directives/map.spec.ts
packages/core/directives/map.ts

correctly disables streetViewControl and zoomControl when
disableDefaultUi is set to true
fixes: #933

fix(AgmMap): respect disableDefaultUI

---

packages/core/services/google-maps-types.ts

- Fixed the values for the enum MapTypeControlStyle to match Google Enum

Issue #1688

---

packages/core/services/maps-api-loader/lazy-maps-api-loader.spec.ts
packages/core/services/maps-api-loader/lazy-maps-api-loader.ts

language config was not working when it is set in forRoot method

fix(Core): Language config bug fixed

---

packages/core/src/lib/services/google-maps-api-wrapper.ts

map events did not get the correct arguments
fixes: #1845

fix(AgmMap): correct arguments to map click events
